### PR TITLE
Adding Go-http-client UA

### PR DESCRIPTION
**Pull request by carlosflorencio**

### CODE REVIEW

**Comment by omrilotan** [comment]
Thank you for this contribution. Could you possibly add a user agent string to [fixture list](https://github.com/omrilotan/isbot/blob/main/tests/fixtures/manual-crawlers-list.yml)?
Our test coverage requires an example for every rule

**Comment by carlosflorencio** [comment]
Done :)

**Comment by omrilotan** [comment]
Thank you, Carlos.
This user agent string is already covered. Please view:
https://isbot.js.org/?ua=Go-http-client/1.1

**Comment by carlosflorencio** [comment]
Ah cool! Will close the PR then, thanks for your time.

**Comment by omrilotan** [comment]
You can see feedback in unit test as well
```
Error: Found issues with 1 rules
    Rule "^go-http" is made redundant by rule "(?<!(lib))http"
```

**Pull request closed without merging**
