### PR TITLE
Add k8s probe bot

### PR DESCRIPTION
**Pull request by Kirkhammetz**
Added Kubernetes probe bot that ping to health-check services

### CODE REVIEW

**Comment by omrilotan** [comment]
Thank you, I appreciate this. Could you possibly add a user agent string to /tests/fixtures/manual-crawlers-list.yml?

**Comment by omrilotan** [comment]
Never mind, I've got a couple of minutes to do it now

**Comment by omrilotan** [comment]
Published on `isbot@3.0.13`

**Comment by Kirkhammetz** [comment]
> Thank you, I appreciate this. Could you possibly add a user agent string to /tests/fixtures/manual-crawlers-list.yml?

Sorry I read it now!

> Published on isbot@3.0.13

Thank you! I really needed this 👍

**Comment by omrilotan** [comment]
Genuinely happy to

**Pull request merged**
